[package]
name = "modal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_enum = "0.2.0"
atomic_float = { git = "https://github.com/kamirr/atomic_float", branch = "main", default-features = false, features = ["serde"] }
anyhow = "1.0.70"
bimap = "0.6.3"
dyn-clone = "1.0.11"
eframe = "=0.19.0"
egui_node_graph = "0.4.0"
num-traits = "0.2"
num-derive = "0.3"
rand = "0.8.5"
rand_distr = "0.4.3"
rodio = "0.17.1"
thunderdome = "0.6.0"
wav = "1.0.0"

serde = { version = "1.0.160", features = ["derive", "rc"] }
erased-serde = "0.3.25"