[package]
name = "modal"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic_enum = "0.2.0"
atomic_float = { git = "https://github.com/kamirr/atomic_float", branch = "main", default-features = false, features = ["serde"] }
anyhow = "1.0.70"
bimap = "0.6.3"
derive_more = "0.99.17"
dyn-clone = "1.0.11"
eframe = { version = "=0.21.0", features = ["persistence"] }
egui-curve-edit = { path = "../egui-curve-edit", features = ["serde"] }
egui_node_graph = { version = "0.4.0", features = ["persistence"] }
midly = "0.5.3"
noise = "0.8.2"
num-traits = "0.2"
num-derive = "0.3"
pid = "4.0.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rfd = "0.11.3"
rodio = "0.17.1"
rustfft = "6.1.0"
strum = { version = "0.24.1", features = ["derive"] }
thunderdome = "0.6.0"
wav = "1.0.0"

serde = { version = "1.0.160", features = ["derive", "rc"] }
serde_json = "1.0.96"
typetag = "0.2.7"

[patch.crates-io]
egui_node_graph = { path = "../egui_node_graph/egui_node_graph" }